### ISSUE TITLE
Can this run on Windows?

### ISSUE THREAD

**Issue by SB2020-eye** [paulbauriegel/doxa_cython#1]
Hi. I have been trying hard to get this working on my Windows 10 64-bit computer in a Conda environment.

The hangup has been around this line from the installation instructions:

`CPPFLAGS=-I$PWD/../Doxa/Doxa python3 setup.py build_ext --inplace`

I would get:

`The term 'CPPFLAGS=-I$PWD/../Doxa/Doxa' is not recognized as a cdmlet, function, script file, or operable program`

This was in Visual Studio Code. In Git Bash, I would get:

`modulenotfounderror` ... `no module named 'cython'`

Yet I have cython; and I nonetheless tried many ways to upgrade it, etc.

(Also, somewhere in that period of time, I was getting `permission denied` -- perhaps using the Ubuntu app for Windows. I am not 100% sure now.)

I am new at python. (So I am kind-of stuck with "cookbook" approaches.) Anyways, after hours with no success, I thought to try the same argument line from your instructions with `python` instead of `python3` (in Visual Studio Code).

This gave a new error:

`Attributeerror: 'msvccompiler' object has no attribute 'compiler_so'`

I did more searching online. From what I could discern, I am now wondering if doxa_cython is able to be installed on Windows at all. Is it?

And if not, is it possible for one to alter the existing code in order to make it work?

Thank you for your time and consideration.

**Comment by brandonmpetty** [comment]
@SB2020-eye , since there hasn't been an update for some time on this repo, or reply to this question, you might check out the recent exp. python support for windows here: https://github.com/brandonmpetty/Doxa/tree/master/Bindings/Python

@paulbauriegel , hopefully you find the Python bindings useful as well.  I have recently made some significant improvements to the library that you might appreciate.  I am very new to python, so I would love your feedback.

**Comment by paulbauriegel** [comment]
@SB2020-eye I'm sorry for overlooking this issue. It kinda slipped through. You're absolutely right I developed the wrapper with only Linux in mind. The problems are the lines 17 and 23 of the `setup.py` script where I'm accessing self.compiler.compiler_so. In order for that to work on Windows, I would have needed to change those lines. However since @brandonmpetty has written an official wrapper, this project has become obsolete by now.
@brandonmpetty Many thanks for this great library. It's truly amazing. I left you a pull request to enable Linux builds as well. Thanks a lot.

**Comment by SB2020-eye** [comment]
Thanks, @paulbauriegel and @brandonmpetty!
